### ISSUE TITLE
Question: What are the goals?

### ISSUE THREAD

**Issue by nikeee** [freetzing/fritzing-js#11]
It seems that this is a JS library for browser-side usage. I have some questions:

- Does this have the goal to create a web-based version of fritzing?
- Possibly using react (reading the other issues)? 
- What's the current status (dead/stale)?

**Comment by karpawich** [comment]
@nikeee Due to the legal rights of the Fritzing organization, we moved all active development to https://github.com/freetzing/freetzing-js.  We are working right now to move through the TODO list you see in the README over the next few weeks.

And yes, we do have plans to develop a web-based Fritzing application. Although, the development for that won't happen until this library has been completed.
