### ISSUE TITLE
Allow saving sketches to indexed.db or localstorage

### ISSUE THREAD

**Issue by oveddan** [freetzing/fritzing-js#17]
It would be cool to make this app work totally from a cdn...and let people save or retrieve sketches from their local storage or indexed db.

**Comment by karpawich** [comment]
@oveddan Glad to see that your interested in the project. **fritzing-js** is actually home to the library that we'll use to convert between the old Fritzing data files and the data model that we put together for the new version that we will host over at the [freetzing](https://github.com/freetzing/freetzing) repo.. you can open and issue there if you'd like.

@el-j are discussing something similar to what you're suggesting, although we are looking to take advantage of the free tools available to open source projects, so we will probably host data either through curated npm or Github repos. If you have a vision for an alternative solution, feel free to elaborate!

For the meantime, I'm closing this specific issue, because it is outside the scope of the particular repo that you opened it on.
